### ISSUE TITLE
tensorflow 1.13 update

### ISSUE THREAD

**Issue by smartinsightsfromdata** [inoryy/tensorflow-optimized-wheels#1]
Kind request:  upgrade to latest cuda & tensorflow

1.13.0 | 10.1 | 7.5 | 3.6 | 2.4.2 | 5.0, 6.1, 7.0 | Linux
-- | -- | -- | -- | -- | -- | --

Many thanks in advance.

**Comment by inoryy** [comment]
Sure, I'll look into it over the weekend.

**Comment by z1277724487** [comment]
I need it too. TXXXXX!!! It's really hard to compile by myself.

**Comment by inoryy** [comment]
I've added TF 1.13.1, but I'll stick with CUDA 10.0 / CuDNN 7.3 for now. I'll probably also build tf 2.0 alpha soon.
