### ISSUE TITLE
failing to download  latest release 

### ISSUE THREAD

**Issue by Sagar19RaoRane** [inoryy/tensorflow-optimized-wheels#10]
failing to download TensorFlow 2.0.0a0, Python 3.7, CUDA 10.0, CuDNN 7.5, TensorRT 5.0, NCCL 2.4 release.  getting HTTP  Error 403

Operating system: Windows 10

**Comment by inoryy** [comment]
Hmm, double checked all of the links - seem to be working fine. Note that I don't have Windows support at the moment.
