### ISSUE TITLE
Error: trying to deallocate null ptr

### ISSUE THREAD

**Issue by mptich** [inoryy/tensorflow-optimized-wheels#11]
TF 1.13.1 
CUDA 10.0 
CUDNN 7.5 
TensorRT 5.0 
Python 3.7.1
NCCL 2.4
GPU: happens on both 1080ti and 2080ti

Running: Yolov3 like model, originally from here:
https://github.com/qqwweee/keras-yolo3
slightly modified.

It runs fine in all other environments (TF 1.12 / CUDA 9.0), and it runs fine in this environment as long as batch size > 1. But when batch size ==1, I am seeing:

2019-04-22 16:29:52.840073: E tensorflow/core/common_runtime/bfc_allocator.cc:373] tried to deallocate nullptr

**Comment by inoryy** [comment]
I'm not sure it's something I could fix. Can you verify this doesn't happen with official TF 1.13.1 build?

**Comment by mptich** [comment]
Thanks Roman, it is indeed happens with official TF 1.13.1 with batch size = 1.
