### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by dimitry-ishenko** [inoryy/tensorflow-optimized-wheels#17]
Wanted to ask if you could share your build instructions. I've build a few wheels, but they all ended up being twice as slow compared to the official binary.

I haven't done full testing with your wheel yet, but it at least seems to run on par with the official one.

To build mine I've followed the official ["Build from source"](https://www.tensorflow.org/install/source) instructions. After running `./configure`, my `.tf_configure.bazelrc` shows:

    build --action_env PYTHON_BIN_PATH="/usr/bin/python"
    build --action_env PYTHON_LIB_PATH="/usr/lib/python3/dist-packages"
    build --python_path="/usr/bin/python"
    build --config=xla
    build --config=tensorrt
    build --action_env CUDA_TOOLKIT_PATH="/usr/local/cuda"
    build --action_env TF_CUDA_COMPUTE_CAPABILITIES="3.5,5.0,6.0,7.0"
    build --action_env GCC_HOST_COMPILER_PATH="/usr/bin/x86_64-linux-gnu-gcc-8"
    build --config=cuda
    build:opt --copt=-march=native
    build:opt --copt=-Wno-sign-compare
    build:opt --host_copt=-march=native
    build:opt --define with_default_optimizations=true
    test --flaky_test_attempts=3
    test --test_size_filters=small,medium
    test:v1 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial
    test:v1 --build_tag_filters=-benchmark-test,-no_oss,-gpu
    test:v2 --test_tag_filters=-benchmark-test,-no_oss,-gpu,-oss_serial,-v1only
    test:v2 --build_tag_filters=-benchmark-test,-no_oss,-gpu,-v1only
    build --action_env TF_CONFIGURE_IOS="0"

My build commands are:

    bazel build --config=opt --config=cuda --copt=-march=haswell --copt=-mtune=haswell --jobs=4 //tensorflow/tools/pip_package:build_pip_package
    ./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/

I am running on a Xeon E5-1630 CPU (haswell) with Quadro K220 GPU (compute cap: 5.0). tf detects all libraries and the GPU, XLA, etc.

Not sure what gives...

**Comment by inoryy** [comment]
Unfortunately I don't have access to the machine I used to build the wheels but I don't recall doing anything special, your config looks fine to me.

Try enabling the SIMD flags, e.g. `--copt=-mfma --copt=-mavx2`, or full MKL suite with `--config=mkl`. In theory, they should be already working via the `march` flag, but maybe worth a try.

**Comment by dimitry-ishenko** [comment]
@inoryy I am pretty sure FMA and AVX2 are enabled. At least according to this:

    gcc -march=haswell -Q --help=target | grep 'mfma\|mavx2'
      -mavx2                      		[enabled]
      -mavx256-split-unaligned-load 	[disabled]
      -mavx256-split-unaligned-store 	[disabled]
      -mfma                       		[enabled]
      -mfma4                      		[disabled]

Also, tf no longer complains about not using them.

I will try enabling MKL. Maybe that's the missing piece. :smile: 

Anyway, thank you for the pointers. If you happen to get your hands on that machine, I could use and updated version of tf (2.2.0rc4 at this moment) with CUDA and python 3.8.

**Comment by dimitry-ishenko** [comment]
@inoryy it turns out I did have MKL enabled and that was the root of the problem. :shrug: Once I've disabled it, I started getting similar performance to vanilla tensorflow builds. Thank you for being there for me. :smile:

**Comment by inoryy** [comment]
That's quite surprising, I would assume Intel CPU would perform better with MKL. Either way, glad you've resolved the issue!

**Comment by dimitry-ishenko** [comment]
That was my assumption too. Just to eliminate error on my side, I've tried the official build of [intel-tensorflow](https://pypi.org/project/intel-tensorflow/) and got the same poor performance. Quick search on the web revealed that I am not the only one and that on some workloads MKL performs worse than vinilla TF. Cheers.
