### ISSUE TITLE
Support for Python 3.7

### ISSUE THREAD

**Issue by filips123** [inoryy/tensorflow-optimized-wheels#2]
Is Python 3.7 supported? The wheels say that only Python 3.6 is supported.
I need TensorFlow 1.12 with AVX  and AVX2 for Python 3.7.

Also, is Windows (10) supported?

**Comment by inoryy** [comment]
No, only Python 3.6 & Linux right now.  
I could look into building for Python 3.7 though I'm not sure TF 1.12 supports it, there was some collision with async, iirc. Don't have any way to build for Windows though.

**Comment by filips123** [comment]
Ok. You could maybe use some CI for Work.

**Comment by pbosch** [comment]
I would partially second the request. Windows support with TF 1.13.1 and Python 3.7 would be nice. And, if possible, TensorRT support. Maybe a switch to Python 3.7 in general? If you have the setup but no Windows environment, I could help with that.

I would not recommend to build TF 1.12 for Python 3.7. There are indeed a lot of issues for this combination. TF 1.13.1 should have no issues with 3.7 though.

**Comment by inoryy** [comment]
I do the builds on an internal machine and unfortunately there's just no simple way to setup Windows environment there. 

I think I will indeed switch to Python 3.7 soon-ish.

**Comment by pbosch** [comment]
As I said, I can help with the Windows part. I have a Windows environment and I should be able to compile it, especially if you already have a repository or something for the setup.

**Comment by inoryy** [comment]
@pbosch If by "setup" you mean something like a Docker image then no, it's all manually configured. You're of course welcome to compile it on Windows if you can get it working. I can try to help with the general steps once you have Python / CUDA / CuDNN / nvcc / gcc / bazel setup.

**Comment by inoryy** [comment]
I've added Tensorflow 1.13.1 + Python 3.7 build. TF 2.0-alpha + Py37 coming next.

**Comment by inoryy** [comment]
TF 2.0 with Python 3.7 is also released, so I'm closing this ticket. We can continue discussing Windows builds in #3.
