### ISSUE TITLE
Compiler flag can cause issues

### ISSUE THREAD

**Issue by pbosch** [inoryy/tensorflow-optimized-wheels#4]
I was wondering if you were aware of the following TF issue: https://github.com/tensorflow/tensorflow/issues/23386
Apparently it helps if --define=framework_shared_object=true is set in bazel. 

I run into this when I was trying to add a tf.nn activaiton function to a tf.keras.model. Something goes wrong while creating the object. I think the Github issue explains it in more detail.

**Comment by inoryy** [comment]
Nope, wasn't aware of this, thanks for bringing it up! Can confirm it happens for the latest two builds since I had to switch to monolithic build due to some bazel bug. Will look into rebuilding them properly.

**Comment by inoryy** [comment]
Alright, I've re-built the latest two wheels (1.13.1 and 2.0.0a) with the suggested fixes. Seems to have solved it for me, can you check if it resolved the issue on your end?

**Comment by pbosch** [comment]
It's resolved. Adding tf.nn activations to tf.keras models works fine. 

I would say the issue is closed.

**Comment by inoryy** [comment]
Great, thanks for confirming!
