### ISSUE TITLE
CUDA=10.1 tensorflow=1.13 python=3.7 please?

### ISSUE THREAD

**Issue by bjarkef** [inoryy/tensorflow-optimized-wheels#6]
Hi. On Ubuntu 18.10 it is only really possible to install cuda 10.1 (not cuda 10.0). Can you provide  a optimized tensorflow-gpu wheel for this combination please? :)

CUDA=10.1 tensorflow=1.13 python=3.7

**Comment by inoryy** [comment]
Hmm, you can install any CUDA version you want on Ubuntu. Just download the appropriate toolkit from [nvidia website](https://developer.nvidia.com/cuda-toolkit-archive) and you're good to go.

The issue with CUDA 10.1 is that it's way too bleeding edge right now, even nvidia's own TensorRT wasn't built against it last I checked.

**Comment by bjarkef** [comment]
You are right thanks, I succeeded in installing CUDA 10.0. However none of the wheels works as my gpu only supports cuda compute capabilities 3.0. I will open a new issue. Thanks for you help.
