### ISSUE TITLE
CUDA=10.0 tensorflow=1.13.1 python=3.7 cuda compute capabilities 3.0

### ISSUE THREAD

**Issue by bjarkef** [inoryy/tensorflow-optimized-wheels#7]
Hi again,

I would like to request almost wheel you already provide, however with cuda compute capabilities 3.0.

CUDA=10.0 tensorflow=1.13.1 python=3.7 cuda compute capabilities=3.0

Thanks in advance. :)

**Comment by inoryy** [comment]
Sure, I can look into that. But can you verify your CPU supports AVX2 / SSE4 flags?

**Comment by inoryy** [comment]
Actually, it seems I can't enable XLA support with CC < 3.5 as they've only recently lifted it to a [soft requirement](https://github.com/tensorflow/tensorflow/issues/26394#ref-commit-8dc2d0e). I'm not sure if I can do a dedicated 3.0 build, do you have any alternative builds you to try?
