### ISSUE TITLE
Tensorflow 1.13.1 CUDA 10.1 Python (3.6 or 3.7)

### ISSUE THREAD

**Issue by ivandatasci** [inoryy/tensorflow-optimized-wheels#8]
Could you please build this wheel?
The motivation is that the latest CUDA release is 10.1. It installs without problem in my hands but CUDA 10.0 fails. I suspect that I am not the only one with this problem.

Thank you.

Ivan

**Comment by inoryy** [comment]
As explained in #6, CUDA 10.1 is too new and doesn't provide any tangible benefits to switch right now.

**Comment by ivandatasci** [comment]
I understand.

That being the case, please consider showing how to build those wheels
rather than providing a wheel for every permutation of software
versions.

If you allowed me a metaphor, I would say that many fish are great but
one fishing rod is even better.

In my particular case, CUDA 10.1 is my only option.

Anyway, thank you for your selfless contributions to the online
community even though you cannot serve all requests.

Best.

Ivan

Ivan Gregoretti, PhD
Bioinformatics
Cell Signaling Technology, Inc
3 Trask Lane
Danvers, MA 01923. USA.
Phone +1-978-867-2429

**Comment by inoryy** [comment]
Why do you think CUDA 10.1 is your only option? What happens if you remove everything CUDA related and install the `*.deb` package from [nvidia's website](https://developer.nvidia.com/cuda-10.0-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal)?

With regards to metaphor - I never really considered it, I assume there are good tutorials available on the internet, and for most people, the main issue with building custom wheels is the computational requirements...

**Comment by ivandatasci** [comment]
My work and the work of my interns is all .rpm-based, not .ded-based.
We use the Fedora family of linux distributions. Very open source philosophy.

My current endevours require building a custom JupyterLab with
GPU-enabled TensorFlow in a docker container. My attempts with CUDA
10.0 only ended in the drivers refusing to install.

To make things a bit more difficult, we need to build and run those
containers on GPU-equiped virtual machines on the Amazon cloud.

Lots of opportunities for frustration, as you can see, but also lots
of opportunities to discover solutions and better prepare interns for
a world that needs them.

Regarding computational requirements, with the Amazon cloud, my group
spins on demand virtual machines of any hardware configuration. The
most expensive machine I have ever used on Amazon was about €2.7 per
hour.

I hope that this explains my original wheel request although I
understand now that it cannot be served.

Thank you.

Ivan

**Comment by inoryy** [comment]
Alright, that makes sense.  
I can look into making a proper docker image, but can't promise an ETA at the moment.
