### ISSUE TITLE
Why pip doesn't show tensorflow-gpu after wheel installation?

### ISSUE THREAD

**Issue by denissato** [inoryy/tensorflow-optimized-wheels#9]
Hello guys! Is it necessary a previous installation of tensorflow-gpu to install these wheels? Sorry, I'm a newbie! My question is because, after the wheel installation, I have two tensorflow versions installed (using `pip show tensorflow` and `pip show tensorflow-gpu`). I don't understand! Does anyone help?

My CPU is Ryzen 2600
GPU - Geforce 1050ti
 
I found this git because I had the AVX2 and FMA issue!

**Comment by inoryy** [comment]
Hello, just uninstall both and then reinstall this wheel. 
It will still show up as `tensorflow` in pip, but supports GPU as well.

**Comment by denissato** [comment]
> Hello, just uninstall both and then reinstall this wheel.
> It will still show up as `tensorflow` in pip, but supports GPU as well.

Thank you very much!
